[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.autoflake]
exclude = ["**/test_files/**"]

[tool.mypy]
exclude = [
    "alembic/versions/*",
    "test_files/*"
]
plugins = ["sqlalchemy.ext.mypy.plugin"]
