name: Lint and Type Check

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run autoflake (check)
        working-directory: backend
        run: |
          autoflake --version
          autoflake --check-diff --recursive --remove-all-unused-imports --remove-unused-variables --expand-star-imports .

      - name: Run isort (check)
        working-directory: backend
        run: |
          isort --version-number
          isort --profile black --check-only --diff .

      - name: Run Black (check)
        working-directory: backend
        run: |
          black --version
          black --check --diff .

      - name: Run mypy
        working-directory: backend
        run: |
          mypy --version
          mypy --strict .